app/evaluation/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.start, name='start'),
]

app/iamDioeVr/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin
from vr import views

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'main/login.html'}, name='iamdioevr_login'),
	url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': reverse_lazy('Vr:start')}, name='iamdioevr_logout'),
	url(r'^$', include('vr.urls', namespace='Vr')),
	url(r'^data/', views.data, name='data'),
	url(r'^updateaudio/', views.updateaudio, name='updateaudio'),
	url(r'^evaluation/', include('evaluation.urls', namespace='evaluation')),
]

app/regionenraten/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin
from vr import views

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'main/login.html'}, name='regionenraten_login'),
	url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': reverse_lazy('Vr:start')}, name='regionenraten_logout'),
	url(r'^$', include('vr.urls', namespace='Vr')),
	url(r'^data/', views.data, name='data'),
	url(r'^updateaudio/', views.updateaudio, name='updateaudio'),
	url(r'^evaluation/', include('evaluation.urls', namespace='evaluation')),
]

app/vr/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.start, name='start'),
]

app/evaluation/models.py
from django.db import models

# Create your models here.

app/evaluation/views.py
from django.shortcuts import render_to_response, redirect
from django.http import HttpResponse
from django.template import RequestContext
import vr.models as dbmodels
import datetime


def start(request):
	"""Startseite."""
	if not request.user.is_authenticated():
		return redirect('regionenraten_login')
	aSeite = 0
	if 'seite' in request.GET and request.GET.get('seite'):
		aSeite = int(request.GET.get('seite'))
	getXls = False
	if 'get' in request.GET and request.GET.get('get') == 'xls':
		getXls = True
	aAuswertungen = []
	prev = -1
	next = -1
	maxPerPage = 14
	aAntwortenM = dbmodels.antworten.objects.all().order_by('-spiel__spieler__zeit', 'spiel__zeit')
	aCount = aAntwortenM.count()
	# Seiten
	if getXls:
		import xlwt
		response = HttpResponse(content_type='text/ms-excel')
		response['Content-Disposition'] = 'attachment; filename="regionenraten_' + datetime.date.today().strftime('%Y%m%d') + '.xls"'
		wb = xlwt.Workbook(encoding='utf-8')
		ws = wb.add_sheet('regionenraten')
		row_num = 0
		columns = []
		columns.append(('Nr', 2000))
		columns.append(('Antworten Id', 2000))
		columns.append(('Antworten beispiel', 2000))
		columns.append(('Antworten wiedergaben', 2000))
		columns.append(('Antworten gewOrt', 2000))
		columns.append(('Antworten hochdeutsch', 2000))
		columns.append(('Antworten orf', 2000))
		columns.append(('Antworten pOrt', 2000))
		columns.append(('Antworten aufgefallen', 2000))
		columns.append(('Antworten zeit', 2000))
		columns.append(('Spiel Id', 2000))
		columns.append(('Spiel Zeit', 2000))
		columns.append(('Audiodatei Id', 2000))
		columns.append(('Audiodatei file', 2000))
		columns.append(('Audiodatei ort', 2000))
		columns.append(('Audiodatei benutzt', 2000))
		columns.append(('Spieler Id', 2000))
		columns.append(('Spieler zeit', 2000))
		columns.append(('Spieler geburtsjahr', 2000))
		columns.append(('Spieler gesch', 2000))
		columns.append(('Spieler taetigkeit', 2000))
		columns.append(('Spieler wohnort', 2000))
		columns.append(('Spieler wohnortLeben', 2000))
		columns.append(('Spieler wohnortEltern', 2000))
		columns.append(('Spieler erkannt', 2000))
		columns.append(('Spieler anmerkungen', 2000))
		font_style = xlwt.XFStyle()
		font_style.font.bold = True
		for col_num in range(len(columns)):
			ws.write(row_num, col_num, columns[col_num][0], font_style)
		font_style = xlwt.XFStyle()
		font_style_datetime = xlwt.XFStyle()
		font_style_datetime.num_format_str = 'YYYY-MM-DD hh:mm:ss'
		for obj in aAntwortenM:
			row_num += 1
			ws.write(row_num, 0, row_num, font_style)
			ws.write(row_num, 1, obj.pk, font_style)
			ws.write(row_num, 2, obj.beispiel, font_style)
			ws.write(row_num, 3, obj.wiedergaben, font_style)
			ws.write(row_num, 4, str(obj.gewOrt), font_style)
			ws.write(row_num, 5, obj.hochdeutsch, font_style)
			ws.write(row_num, 6, obj.orf, font_style)
			ws.write(row_num, 7, obj.pOrt, font_style)
			ws.write(row_num, 8, obj.aufgefallen, font_style)
			ws.write(row_num, 9, obj.zeit, font_style_datetime)
			ws.write(row_num, 10, obj.spiel.pk, font_style)
			ws.write(row_num, 11, obj.spiel.zeit, font_style_datetime)
			ws.write(row_num, 12, obj.audiodatei.pk, font_style)
			ws.write(row_num, 13, obj.audiodatei.file, font_style)
			ws.write(row_num, 14, str(obj.audiodatei.ort), font_style)
			ws.write(row_num, 15, obj.audiodatei.benutzt, font_style)
			ws.write(row_num, 16, obj.spiel.spieler.pk, font_style)
			ws.write(row_num, 17, obj.spiel.spieler.zeit, font_style_datetime)
			ws.write(row_num, 18, obj.spiel.spieler.geburtsjahr, font_style)
			ws.write(row_num, 19, obj.spiel.spieler.gesch, font_style)
			ws.write(row_num, 20, obj.spiel.spieler.taetigkeit, font_style)
			ws.write(row_num, 21, str(obj.spiel.spieler.wohnort), font_style)
			ws.write(row_num, 22, str(obj.spiel.spieler.wohnortLeben), font_style)
			ws.write(row_num, 23, obj.spiel.spieler.wohnortEltern, font_style)
			ws.write(row_num, 24, obj.spiel.spieler.erkannt, font_style)
			ws.write(row_num, 25, obj.spiel.spieler.anmerkungen, font_style)
		wb.save(response)
		return response
	else:
		if aSeite > 0:
			prev = aSeite - 1
		if aCount > (aSeite + 1) * maxPerPage:
			next = aSeite + 1
		# Antworten ... weiter
		aNr = aSeite * maxPerPage
		for aAntwort in aAntwortenM[aSeite * maxPerPage:aSeite * maxPerPage + maxPerPage]:
			aNr += 1
			aAuswertungen.append({'aNr': aNr, 'model': aAntwort})

		return render_to_response('evaluation/auswertungstart.html', RequestContext(request, {'aAuswertungen': aAuswertungen, 'aCount': aCount, 'prev': prev, 'next': next}))

app/evaluation/templates/evaluation/auswertungstart.html
{% extends 'main/basis.html' %}
{% load staticfiles %}
{% load regionenratenTags %}
{% load crispy_forms_tags %}
{% block title %} - Auswertung{% endblock %}
{% block ueberschrift %} - Auswertung{% endblock %}
{% block sitecss %}<link href="{% static "evaluation/css/style.css" %}?{% settings_value "CACH_RANDOM" %}" rel="stylesheet">{% endblock %}
{% block inhalt %}
<div style="overflow-x: auto">
	<a href="{% url 'regionenraten_logout' %}" class="float-right">Abmelden</a><h1>Auswertung</h1>
	<br>
	{% if aAuswertungen %}
		<b>Treffer: {{ aCount }}</b> - {% if prev > -1 %}<a href="{% url 'evaluation:start' %}?seite={{ prev }}">Zurück</a>{% else %}Zurück{% endif %} - {% if next > -1 %}<a href="{% url 'evaluation:start' %}?seite={{ next }}">Weiter</a>{% else %}Weiter{% endif %} - <a href="{% url 'evaluation:start' %}?get=xls">XLS</a><br>
		<br>
		<table class="table table-bordered" style="width: auto; max-width: inherit; min-width: 100%; white-space: nowrap;">
			<thead>
				<tr>
					<th>#</th>
					<th>Antworten Id</th>
					<th>Antworten beispiel</th>
					<th>Antworten wiedergaben</th>
					<th>Antworten gewOrt</th>
					<th>Antworten hochdeutsch</th>
					<th>Antworten orf</th>
					<th>Antworten pOrt</th>
					<th>Antworten aufgefallen</th>
					<th>Antworten zeit</th>
					<th>Spiel Id</th>
					<th>Spiel Zeit</th>
					<th>Audiodatei Id</th>
					<th>Audiodatei file</th>
					<th>Audiodatei ort</th>
					<th>Audiodatei benutzt</th>
					<th>Spieler Id</th>
					<th>Spieler zeit</th>
					<th>Spieler geburtsjahr</th>
					<th>Spieler gesch</th>
					<th>Spieler taetigkeit</th>
					<th>Spieler wohnort</th>
					<th>Spieler wohnortLeben</th>
					<th>Spieler wohnortEltern</th>
					<th>Spieler erkannt</th>
					<th>Spieler anmerkungen</th>
				</tr>
			</thead>
			<tbody>
			{% for auswertung in aAuswertungen %}
				<tr>
					<td>{{ auswertung.aNr }}</td>
					<td>{{ auswertung.model.pk }}</td>
					<td>{{ auswertung.model.beispiel }}</td>
					<td>{{ auswertung.model.wiedergaben }}</td>
					<td>{{ auswertung.model.gewOrt }}</td>
					<td>{{ auswertung.model.hochdeutsch }}</td>
					<td>{{ auswertung.model.orf }}</td>
					<td>{{ auswertung.model.pOrt }}</td>
					<td>{{ auswertung.model.aufgefallen }}</td>
					<td>{{ auswertung.model.zeit|date:"c" }}</td>
					<td>{{ auswertung.model.spiel.pk }}</td>
					<td>{{ auswertung.model.spiel.zeit|date:"c" }}</td>
					<td>{{ auswertung.model.audiodatei.pk }}</td>
					<td>{{ auswertung.model.audiodatei.file }}</td>
					<td>{{ auswertung.model.audiodatei.ort }}</td>
					<td>{{ auswertung.model.audiodatei.benutzt }}</td>
					<td>{{ auswertung.model.spiel.spieler.pk }}</td>
					<td>{{ auswertung.model.spiel.spieler.zeit|date:"c" }}</td>
					<td>{{ auswertung.model.spiel.spieler.geburtsjahr }}</td>
					<td>{{ auswertung.model.spiel.spieler.gesch }}</td>
					<td>{{ auswertung.model.spiel.spieler.taetigkeit }}</td>
					<td>{{ auswertung.model.spiel.spieler.wohnort }}</td>
					<td>{{ auswertung.model.spiel.spieler.wohnortLeben }}</td>
					<td>{{ auswertung.model.spiel.spieler.wohnortEltern }}</td>
					<td>{{ auswertung.model.spiel.spieler.erkannt }}</td>
					<td>{{ auswertung.model.spiel.spieler.anmerkungen }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	{% endif %}
</div>
{% endblock %}
{% block sitejs %}
{% endblock %}